# Generated by Django 5.1.3 on 2024-11-29 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_alter_recipe_recipe_ingridents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_ingridents',
            field=models.TextField(),
        ),
    ]
