# Generated by Django 5.1.3 on 2024-11-30 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0003_alter_recipe_recipe_ingridents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='needs_update',
        ),
    ]
